# Configuration is going to be deleted / moved / optimized.


DigitalOcean:
    api_key: ""
    defaults: #Uses defaults if not specified in server initconfig file.
        #Uses defaults if not specified in server init config.
        #Special Variables you can use:
        #$$Provider$$ = Uses the first available provider.
        name: "$$Provider$$_$$NumberOfServers$$" #Uses provider and num of servers.
        provider:
        region: "$$random_region$$"
        size: ""
        image: ""
        ssh_keys: []
        backups: False #Boolean
        ipv6: False #Boolean
        private_networking: False
        user_data: ""



    Servers: #Keeps track of all server files that were initialized.
        example_digitalocean:
            provider: "digitalocean"
            networking:
                ip: ""
            api:
                id:
                name:
                memory:
                vcpus:
                disk:
                locked:
                created_at:
                status:
                backup_ids: [ ]
                snapshot_ids: [ ]
                features: [ ]
                region:
                image:
                size:
                size_slug:
                networks:
                kernel:
                next_backup_window:
            user_values:
                name: ""
                region: ""
                size: ""
                image: ""
                ssh_keys: []
                backups: False #Boolean
                ipv6: False #Boolean
                private_networking: False
                user_data: ""
