#Configuration file for ark.

general:
  start_at_boot: true
  auto_update: true
  install_directory: "/home/user"
  rcon: true #REQUIRED

#Networking Settings
network:
  host_ip: "127.0.0.1"

players:
  admins: "SteamName, SteamName2"
  whitelist: "SteamName, SteamName2"
  blacklist: "Tr0ll523" #Banned players

session:
  name: "MyDashServer"
  port: 7777
  players_max: 50
  admin_password: "changeme"
  PVE: true
  PVP: false

arkworld:
  auto_save: true
    frequency: 15 #minutes
  auto_backup: true
    frequency: 60 #minutes
    path: "/home/you/ark_server/backup"
