#Configuration file for ark.

#Networking Settings
network:
  host_ip: "127.0.0.1"
  host_port: 7777

# Ark Specific Parameters

server_name: "MyArkServer" #Appears on the public host list.
admin_users: "SteamName"
admin_password: "changeme"
players_max: 50
PVE: true
PVP: false

automatic_save: true
automatic_save_time: 15 #In minutes, will save every 15 minutes.
automatic_backup: false
automatic_backup_path: "~/backup/ark"
automatic_backup_time: 60 #In minutes
automatic_update: false
start_at_boot: false
